import turtle

length = 20
angle = 25
pen = turtle.Turtle()
pen.speed(0)
turtle.tracer(2, 0)

colors = ["#cba6f7", "#5d9b58", "#cba6f7", "#a6e3a1"]
color_index = 0
color = colors[color_index]

def cpz(pensize):
  return pensize - 0

turtle.bgcolor("#1e1e2e")
pen.pencolor(color)
pen.pensize(4)

pen.penup()
pen.goto(300, -300)
pen.pendown()
pen.left(90)


# Stack for push/pop operations
stack = []

pen.left(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.forward(length)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.forward(length)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.forward(length)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.forward(length)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.forward(length)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.forward(length)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
pen.forward(length)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.forward(length)
pen.left(angle)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.right(angle)
pen.forward(length)
stack.append((pen.position(), pen.heading(), pen.pensize()))
pen.pensize(max(1, cpz(pen.pensize())))
pen.right(angle)
pen.forward(length)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pos, ang, pensize = stack.pop()
pen.penup()
pen.setposition(pos)
pen.setheading(ang)
pen.pendown()
pen.pensize(max(1, cpz(pensize)))
pen.left(angle)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)
pen.pensize(2)
pen.fillcolor(color)
pen.begin_fill()
pen.circle(30, 60)
pen.left(120)
pen.circle(30, 60)
pen.left(120)
pen.end_fill()
pen.pensize(2)
color_index = (color_index + 1) % 4
color = colors[color_index]
pen.pencolor(color)

turtle.done()
